    
spring:
  datasource:
    db1:
      url: jdbc:postgresql://localhost:5432/sathish
      username: postgres
      password: Sathish@123
    db2:
      url: jdbc:postgresql://localhost:5432/kumar
      username: postgres
      password: Sathish@123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true

